### PR TITLE
update devcontainer to .net 8

### PR DESCRIPTION
**Pull request by suchja**
updates to .NET 8 based on the updated devcontainer/dotnet. As there is no tag 0-8.0, I switched to 1-8.0.

### CODE REVIEW

**Comment by suchja** [comment]
@microsoft-github-policy-service agree

**Review by IliasDeros — APPROVED** [review]
These changes were compatible with my .NET 8 project

**Review by samruddhikhandale — DISMISSED** [review]
Thanks!

**Review by samruddhikhandale — APPROVED** [review]

**Comment by samruddhikhandale** [comment]
@bamurtaugh would you be able to help approve as part of `Community PR Approvals`? Thanks!

**Review by bamurtaugh — APPROVED** [review]
Thanks!

**Pull request merged**
